name: Build Custom Kernel Vince A10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison flex libssl-dev libelf-dev \
            build-essential gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi make git

      - name: Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          mkdir -p out
          make O=out vince-stock_defconfig
          make O=out -j$(nproc)

      - name: Upload kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: out/arch/arm64/boot/Image
